/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import DAO.QL_BCTT;
import java.awt.BorderLayout;
import java.awt.Color;
import java.math.BigDecimal;
import javax.swing.JOptionPane;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PiePlot;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author Tiến Mạnh
 */
public class BaoCaoThongKe_Chart extends javax.swing.JFrame {
    String where ;
    QL_BCTT bctt =new QL_BCTT();
    public BaoCaoThongKe_Chart() {
        initComponents();
        setLocationRelativeTo(null);
        showPieChart();
        showTS();
        
    }
    public void showPieChart(){
        
        //create dataset
      DefaultPieDataset barDataset = new DefaultPieDataset( );
      barDataset.setValue( "Tiền mặt" , bctt.HTTT("N'Tiền mặt'") );  
      barDataset.setValue( "Thẻ tín dụng" , bctt.HTTT("N'Thẻ tín dụng'") );  
      //barDataset.setValue( "Không Mua " , new Double( 111 ) ); 

      
      //create chart
       JFreeChart piechart = ChartFactory.createPieChart("Hình thức thanh toán",barDataset, false,true,false);//explain
      
        PiePlot piePlot =(PiePlot) piechart.getPlot();
      
       //changing pie chart blocks colors
      // piePlot.setSectionPaint("Mua trực tiếp", new Color(255,255,102));
        //piePlot.setSectionPaint("Mua online", new Color(102,255,102));
        //piePlot.setSectionPaint("MotoG", new Color(255,102,153));
        //piePlot.setSectionPaint("Nokia Lumia", new Color(0,204,204));
      
       
        piePlot.setBackgroundPaint(Color.white);
        
        //create chartPanel to display chart(graph)
        ChartPanel barChartPanel = new ChartPanel(piechart);
        panelBarChart.removeAll();
        panelBarChart.add(barChartPanel, BorderLayout.CENTER);
        panelBarChart.validate();
    }
    public void showTS(){
        loc();
        String query="SELECT SUM(TONGTIEN)  FROM HD ";
        BigDecimal doanhThu =new BigDecimal(bctt.thongSo(query+where));
        
        lbDoanhTHu.setText(""+doanhThu);
        
        query ="DECLARE @TT float \n" +
"	SELECT @TT = Sum(tongtien) from hd \n" +where+
"	SELECT @TT -SUM(CT.SL *MH.GIANHAP)  FROM CHITIETHD CT INNER JOIN MATHANG MH ON MH.MAMH =CT.MAMH"
                + " INNER JOIN HD ON HD.MAHD =CT.MAHD";
        BigDecimal loiNhuan =new BigDecimal(bctt.thongSo(query+where));
        lblLoiNHuan.setText(""+loiNhuan);
        query ="SELECT COUNT(MAHD) FROM HD ";
        
        lblSHD.setText(""+bctt.thongSo(query+where));
    }
    public void loc(){
        int chon =cbxChoose.getSelectedIndex();
        switch(chon){
            case -1:
                break;
            case 0: where =" where DateDiff(dd,HD.THOIGIAN,getdate())=0";
            break;
            case 1: where =" where DateDiff(dd,HD.THOIGIAN,getdate())=1";
            break;
            case 2: where =" where DateDiff(wk,HD.THOIGIAN,getdate())=0";
            break;
            case 3: where =" where DateDiff(wk,HD.THOIGIAN,getdate()) = 1";
            break;
            case 4: where =" where DateDiff(mm,HD.THOIGIAN,getdate()) = 0";
            break;
            case 5: where =" where DateDiff(mm,HD.THOIGIAN,getdate()) = 1";
            break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelBarChart = new javax.swing.JPanel();
        cbxChoose = new javax.swing.JComboBox<>();
        lblLoiNHuan = new javax.swing.JLabel();
        lbDoanhTHu = new javax.swing.JLabel();
        lblSHD = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblMau1 = new javax.swing.JLabel();
        lblMau3 = new javax.swing.JLabel();
        lblMau2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarChart.setBackground(new java.awt.Color(255, 255, 255));
        panelBarChart.setLayout(new java.awt.BorderLayout());
        jPanel1.add(panelBarChart, new org.netbeans.lib.awtextra.AbsoluteConstraints(622, 32, 396, 309));

        cbxChoose.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hôm nay", "Hôm qua", "Tuần hiện tại", "Tuần trước", "Tháng này", "Tháng trước" }));
        cbxChoose.setToolTipText("");
        cbxChoose.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxChooseItemStateChanged(evt);
            }
        });
        jPanel1.add(cbxChoose, new org.netbeans.lib.awtextra.AbsoluteConstraints(793, 359, 169, -1));

        lblLoiNHuan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLoiNHuan.setForeground(new java.awt.Color(255, 255, 255));
        lblLoiNHuan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoiNHuan.setText("jLabel2");
        jPanel1.add(lblLoiNHuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 90, -1, -1));

        lbDoanhTHu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbDoanhTHu.setForeground(new java.awt.Color(255, 255, 255));
        lbDoanhTHu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbDoanhTHu.setText("jLabel2");
        jPanel1.add(lbDoanhTHu, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));

        lblSHD.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSHD.setForeground(new java.awt.Color(255, 255, 255));
        lblSHD.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSHD.setText("1");
        jPanel1.add(lblSHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Số hóa Đơn ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Doanh Thu ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Lợi nhuận ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, -1, -1));

        lblMau1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AnhMau2.png"))); // NOI18N
        lblMau1.setText("jLabel3");
        jPanel1.add(lblMau1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 190, 110));

        lblMau3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Layer 1.png"))); // NOI18N
        lblMau3.setText("jLabel3");
        jPanel1.add(lblMau3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 190, 110));

        lblMau2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/AnhMau1.png"))); // NOI18N
        lblMau2.setText("jLabel3");
        jPanel1.add(lblMau2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 190, 110));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1030, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbxChooseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxChooseItemStateChanged
        loc();
        showTS();
    }//GEN-LAST:event_cbxChooseItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe_Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe_Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe_Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BaoCaoThongKe_Chart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BaoCaoThongKe_Chart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbxChoose;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbDoanhTHu;
    private javax.swing.JLabel lblLoiNHuan;
    private javax.swing.JLabel lblMau1;
    private javax.swing.JLabel lblMau2;
    private javax.swing.JLabel lblMau3;
    private javax.swing.JLabel lblSHD;
    private javax.swing.JPanel panelBarChart;
    // End of variables declaration//GEN-END:variables
}
