/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import Models.Account;
import DAO.QL_Account;
import Form.TestMenu.Main;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Tiến Mạnh
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    int a=1,b=1,c=1;
    public Login() {
        initComponents();
        new Chao(this, true).setVisible(true);
        setBackground(new Color(0, 0, 0,0));    // (1)
        jPanel1.setBackground(new Color(0, 0, 0,0));//(2)   (1) VÀ (2) CÙNG NHAU ĐỂ tắt nền
        setLocationRelativeTo(null);
        txtUserName.setBackground(new Color(0, 0, 0,0));
         txtPassword.setBackground(new Color(0, 0, 0,0));
          txtPasswordConFirm.setBackground(new Color(0, 0, 0,0));
          
          txtPasswordConFirm.setVisible(false);
          lblconfirmPassword.setVisible(false);
          SeparatorCuoi.setVisible(false);
          chkCheck.setVisible(false);
          lblDieuKhoan.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        SeparatorCuoi = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtPasswordConFirm = new javax.swing.JPasswordField();
        txtPassword = new javax.swing.JPasswordField();
        txtUserName = new javax.swing.JTextField();
        lblconfirmPassword = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lblDangNhap = new javax.swing.JLabel();
        chkCheck = new javax.swing.JCheckBox();
        lblDieuKhoan = new javax.swing.JLabel();
        lbldangKy = new javax.swing.JLabel();
        lblMenuDangNhap = new javax.swing.JLabel();
        lblMenuSignUp = new javax.swing.JLabel();
        lblminimizeSize = new javax.swing.JLabel();
        lblTB3 = new javax.swing.JLabel();
        lblExitt = new javax.swing.JLabel();
        lblTB1 = new javax.swing.JLabel();
        lblTB2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblRight = new javax.swing.JLabel();
        lblLeft = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 90, 40));

        SeparatorCuoi.setBackground(new java.awt.Color(51, 51, 51));
        SeparatorCuoi.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(SeparatorCuoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 490, 490, 20));

        jSeparator2.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 490, 20));

        txtPasswordConFirm.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPasswordConFirm.setForeground(new java.awt.Color(153, 153, 153));
        txtPasswordConFirm.setText("jPasswordField1");
        txtPasswordConFirm.setBorder(null);
        txtPasswordConFirm.setOpaque(false);
        txtPasswordConFirm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordConFirmMouseClicked(evt);
            }
        });
        jPanel1.add(txtPasswordConFirm, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 490, 40));

        txtPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(153, 153, 153));
        txtPassword.setText("jPasswordField1");
        txtPassword.setBorder(null);
        txtPassword.setOpaque(false);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 490, 40));

        txtUserName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtUserName.setForeground(new java.awt.Color(153, 153, 153));
        txtUserName.setText("Enter username");
        txtUserName.setBorder(null);
        txtUserName.setOpaque(false);
        txtUserName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtUserNameFocusGained(evt);
            }
        });
        txtUserName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUserNameMouseClicked(evt);
            }
        });
        txtUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserNameActionPerformed(evt);
            }
        });
        jPanel1.add(txtUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, 490, 40));

        lblconfirmPassword.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblconfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblconfirmPassword.setText("Confirm Password:");
        jPanel1.add(lblconfirmPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 410, 130, 40));

        jSeparator3.setBackground(new java.awt.Color(51, 51, 51));
        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 380, 490, 10));

        lblDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDangNhap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnLoginSwitch.png"))); // NOI18N
        lblDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangNhapMouseClicked(evt);
            }
        });
        jPanel1.add(lblDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, -1, -1));

        chkCheck.setBackground(new java.awt.Color(102, 51, 255));
        chkCheck.setForeground(new java.awt.Color(51, 51, 255));
        chkCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkCheckActionPerformed(evt);
            }
        });
        jPanel1.add(chkCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, -1, -1));

        lblDieuKhoan.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblDieuKhoan.setForeground(new java.awt.Color(255, 255, 255));
        lblDieuKhoan.setText("Agree");
        jPanel1.add(lblDieuKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 520, 50, -1));

        lbldangKy.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbldangKy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbldangKyMouseClicked(evt);
            }
        });
        jPanel1.add(lbldangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 580, -1, -1));

        lblMenuDangNhap.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuDangNhap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuDangNhapMouseClicked(evt);
            }
        });
        jPanel1.add(lblMenuDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 110, -1, -1));

        lblMenuSignUp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblMenuSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblMenuSignUpMouseClicked(evt);
            }
        });
        jPanel1.add(lblMenuSignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 110, -1, -1));

        lblminimizeSize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblminimizeSizeMouseClicked(evt);
            }
        });
        jPanel1.add(lblminimizeSize, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        lblTB3.setForeground(new java.awt.Color(255, 255, 0));
        jPanel1.add(lblTB3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, -1, -1));

        lblExitt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/anhExit.png"))); // NOI18N
        lblExitt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblExittMouseClicked(evt);
            }
        });
        jPanel1.add(lblExitt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 600, -1, -1));

        lblTB1.setForeground(new java.awt.Color(255, 204, 0));
        jPanel1.add(lblTB1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 290, -1, -1));

        lblTB2.setForeground(new java.awt.Color(255, 204, 0));
        jPanel1.add(lblTB2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Username:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 90, 40));

        lblRight.setForeground(new java.awt.Color(255, 255, 255));
        lblRight.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rightPanel_1.png"))); // NOI18N
        jPanel1.add(lblRight, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 0, 680, 760));

        lblLeft.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLeft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/BaoCao.png"))); // NOI18N
        jPanel1.add(lblLeft, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 50, 620, 660));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 12, 1220, 790));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPasswordConFirmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordConFirmMouseClicked
        if (c==1) {
            txtPasswordConFirm.setText("");
            c=2;
        }
        txtPasswordConFirm.setForeground(Color.white);
    }//GEN-LAST:event_txtPasswordConFirmMouseClicked

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        if (b==1) {
            txtPassword.setText("");
            b=2;
        }
        txtPassword.setForeground(Color.white);
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtUserNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtUserNameFocusGained

    }//GEN-LAST:event_txtUserNameFocusGained

    private void txtUserNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUserNameMouseClicked

        if(a==1){
            txtUserName.setText("");
            a=2;
        }
        txtUserName.setForeground(Color.white);
        //lblTB1.setText("");
    }//GEN-LAST:event_txtUserNameMouseClicked

    private void txtUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserNameActionPerformed

    private void lblDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangNhapMouseClicked
        try {
            this.lblTB3.setText("");
            if(txtUserName.getText().trim().equals("")){
                lblTB1.setText("Tên không được để trống!");
                return;
            }
            else{
                lblTB1.setText("");
            }

            if(txtPassword.getText().trim().equals("")){
                lblTB2.setText("Mật khẩu không được để trống!");
                return;
            }
            else{
                lblTB2.setText("");
            }
            
            QL_Account a =new QL_Account();
            Account acc =a.checkLogin(txtUserName.getText(), txtPassword.getText());
           if(acc ==null){
                JOptionPane.showMessageDialog(this, "Tên đăng nhập hoặc mật khẩu không đúng");
                return;
            }
                       else {
               JOptionPane.showMessageDialog(this,"Đăng nhập thành công");
               Main main =new Main();
               main.setVisible(true);
                this.dispose();
//                role =new Role();
//                role.setVisible(true);
            }
 


        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_lblDangNhapMouseClicked

    private void chkCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkCheckActionPerformed

    }//GEN-LAST:event_chkCheckActionPerformed

    private void lbldangKyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbldangKyMouseClicked
        if(!txtPassword.getText().equals(txtPasswordConFirm.getText())){
            lblTB3.setText("Hai mật khẩu phải giống nhau!");
            return;
        }
        if(chkCheck.isSelected()==false){
            lblTB3.setText("Phải đồng ý với điều khoản của t");
            return;
        }

//        AddUser au =new AddUser();
//        User user = au.dangKyTK(txtUserName.getText(), txtPassword.getText());
        JOptionPane.showMessageDialog(this, "Đăng kí thành công!");
        txtPasswordConFirm.setVisible(false);
        lblconfirmPassword.setVisible(false);
        lbldangKy.setVisible(false);
        lblDangNhap.setVisible(true);
        SeparatorCuoi.setVisible(false);
        lblTB3.setText("");
        lblDieuKhoan.setText("");
        chkCheck.setVisible(false);
    }//GEN-LAST:event_lbldangKyMouseClicked

    private void lblMenuDangNhapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuDangNhapMouseClicked
        //this.login();
    }//GEN-LAST:event_lblMenuDangNhapMouseClicked

    private void lblMenuSignUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblMenuSignUpMouseClicked
        //this.signUp();
    }//GEN-LAST:event_lblMenuSignUpMouseClicked

    private void lblminimizeSizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblminimizeSizeMouseClicked
        setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_lblminimizeSizeMouseClicked

    private void lblExittMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExittMouseClicked
        // Bye bye =new Bye();
        //bye.setVisible(true);
        System.exit(0);
    }//GEN-LAST:event_lblExittMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator SeparatorCuoi;
    private javax.swing.JCheckBox chkCheck;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblDangNhap;
    private javax.swing.JLabel lblDieuKhoan;
    private javax.swing.JLabel lblExitt;
    private javax.swing.JLabel lblLeft;
    private javax.swing.JLabel lblMenuDangNhap;
    private javax.swing.JLabel lblMenuSignUp;
    private javax.swing.JLabel lblRight;
    private javax.swing.JLabel lblTB1;
    private javax.swing.JLabel lblTB2;
    private javax.swing.JLabel lblTB3;
    private javax.swing.JLabel lblconfirmPassword;
    private javax.swing.JLabel lbldangKy;
    private javax.swing.JLabel lblminimizeSize;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JPasswordField txtPasswordConFirm;
    private javax.swing.JTextField txtUserName;
    // End of variables declaration//GEN-END:variables
}
